# Project information
site_name: 'Idylle'
site_description: 'Presentation and Documentation of the micro-framework'
site_author: 'Digipolitan'
site_url: 'https://digipolitan.github.io/Idylle/'

# Repository
repo_name: 'Digipolitan/idylle'
repo_url: 'https://github.com/digipolitan/idylle'

# Copyright
copyright: 'Copyright &copy; 2017 - 2018'

# Documentation and theme
theme: 'material'

# Options
extra:
  logo: 'images/logo.svg'
  palette:
    primary: 'Teal'
    accent: 'Pink'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  social:
    - type: 'github'
      link: 'https://github.com/julien-sarazin'
    - type: 'twitter'
      link: 'https://twitter.com/julien-sarazin'
    - type: 'linkedin'
      link: 'https://de.linkedin.com/in/julien-sarazin-25b89047'
  disqus: 'idylle-1'

# Extensions
markdown_extensions:
  - admonition
  - codehilite(guess_lang=false,linenums=true)
  - toc(permalink=true)
  - pymdownx.arithmatex
  - pymdownx.betterem(smart_enable=all)
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist(custom_checkbox=true)
  - pymdownx.tilde

pages:
    - Introduction: index.md
    - Getting Started: getting-started.md
    - Architecture: architecture.md
    - Dependencies: dependencies.md
