# Project information
site_name: 'Idylle'
site_description: 'Presentation and Documentation of the micro-framework'
site_author: 'Julien Sarazin'
site_url: 'https://julien-sarazin.github.io/idylle'

# Repository
repo_name: 'julien-sarazin/Idylle'
repo_url: 'https://github.com/julien-sarazin/Idylle'

# Copyright
copyright: 'Copyright &copy; 2016 - 2018 Julien Sarazin'

# Documentation and theme
theme: 'material'

# Options
extra:
  logo: 'images/logo.svg'
  palette:
    primary: 'Pink'
    accent: 'Amber'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  social:
    - type: 'github'
      link: 'https://github.com/john-doe'
    - type: 'twitter'
      link: 'https://twitter.com/jonh-doe'
    - type: 'linkedin'
      link: 'https://de.linkedin.com/in/john-doe'

# Google Analytics
google_analytics:
  - 'UA-XXXXXXXX-X'
  - 'auto'

# Extensions
markdown_extensions:
  - admonition
  - codehilite(guess_lang=false,linenums=true)
  - toc(permalink=true)

pages:
    - Idylle: index.md
    - Getting Started: getting-started.md
    - Architecture: architecture.md
    - Dependencies: dependencies.md
